In [53]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/titanic/train.csv
/kaggle/input/titanic/test.csv
/kaggle/input/titanic/gender_submission.csv

In [54]:
train_df = pd.read_csv("/kaggle/input/titanic/train.csv", index_col=0)
test_df = pd.read_csv("/kaggle/input/titanic/test.csv", index_col=0)

In [55]:
train_df = train_df.drop(["Name", "Ticket", "Cabin"], axis=1)

In [56]:
test_df = test_df.drop(["Name", "Ticket", "Cabin"], axis=1)

In [57]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

for item in train_df.columns:
    if item == "Sex" or item == "Embarked":
        le.fit(train_df[item])
        train_df[item] = le.transform(train_df[item])
for item in test_df.columns:
    if item == "Sex" or item == "Embarked":
        le.fit(test_df[item])
        test_df[item] = le.transform(test_df[item])

In [58]:
train_df.dropna(inplace=True)
test_df.interpolate(method='linear', inplace=True)
test_df.fillna(method="ffill", inplace=True)
test_df.fillna(method="bfill", inplace=True)

In [59]:
X_train = train_df.drop("Survived", axis=1)
y_train = train_df["Survived"]

In [60]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(random_state=0)
tree_clf.fit(X_train, y_train)
y_pred = tree_clf.predict(test_df)
print(y_pred)

[0 0 1 1 0 0 0 0 1 0 0 0 1 1 1 1 0 1 0 0 1 1 1 1 1 0 1 1 1 0 0 0 1 0 1 0 0
 0 0 1 0 1 0 1 1 0 0 0 1 1 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 1 1 0 0 0
 1 0 0 0 0 1 1 0 1 0 0 0 1 1 1 1 0 0 0 0 1 0 1 0 1 0 1 0 1 0 1 0 1 1 0 0 0
 0 1 1 1 0 1 1 0 1 1 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 1 0 1 1 1 0
 1 0 1 0 0 1 0 0 1 1 1 1 1 1 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 1 1 0 1 1 1 1
 0 1 0 0 0 0 1 0 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0 1 0 1 0 0 1 0 0 0 0 1 0 1 0
 1 1 1 0 0 0 0 0 0 1 0 1 0 0 1 1 1 1 1 1 1 0 0 0 1 0 1 1 1 0 0 0 0 0 1 0 0
 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 1 1 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1 0 0 0 0 0
 1 1 0 0 0 0 0 0 0 1 0 1 0 0 0 1 0 0 1 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 0 0
 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 1 1 0 0 0 1 1 1 0 0 0 0 1 1 1 1 1 0 0 1 0
 0 1 0 0 1 1 0 0 0 1 1 1 0 0 0 1 0 0 1 0 0 1 1 0 0 1 0 1 0 0 1 0 1 0 0 0 1
 0 1 1 0 1 1 0 1 0 0 0]

In [61]:
pred_df = pd.DataFrame(y_pred, index=test_df.index, columns=["Survived"])
pred_df

             Survived
PassengerId
892                 0
893                 0
894                 1
895                 1
896                 0
...               ...
1305                0
1306                1
1307                0
1308                0
1309                0

[418 rows x 1 columns]

In [62]:
pred_df.to_csv("submission.csv")